branch-defaults:
  master:
    environment: Upnextapidev-env
environment-defaults:
  Upnextapidev-env:
    branch: null
    repository: null
global:
  application_name: upnext-api-dev
  default_ec2_keyname: null
  default_platform:
    arn:aws:elasticbeanstalk:us-west-2::platform/Node.js 14 running
    on 64bit Amazon Linux 2/5.3.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
